/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattleStats { 'winsCount' : bigint, 'bestStreak' : bigint }
export interface BestScores {
  'car' : bigint,
  'farming' : bigint,
  'endlessRun' : bigint,
  'battle' : bigint,
  'cityBuilder' : bigint,
  'indoor' : bigint,
}
export type CropType = { 'tomato' : null } |
  { 'carrot' : null } |
  { 'wheat' : null };
export type GameMode = { 'car' : null } |
  { 'farming' : null } |
  { 'endlessRun' : null } |
  { 'battle' : null } |
  { 'cityBuilder' : null } |
  { 'indoor' : null };
export type GameRunState = { 'start' : null } |
  { 'gameOver' : null } |
  { 'running' : null };
export interface GameState {
  'mode' : GameMode,
  'score' : bigint,
  'state' : GameRunState,
  'coinsEarned' : bigint,
}
export interface MinigameScores {
  'puzzleGame' : bigint,
  'reactionGame' : bigint,
}
export interface PlayerProfile {
  'cityLayout' : [] | [Array<Array<StructureType>>],
  'lastPlayed' : Time,
  'minigameScores' : [] | [MinigameScores],
  'farmPlots' : [] | [Array<Array<[] | [CropType]>>],
  'displayName' : [] | [string],
  'bestTime' : [] | [bigint],
  'totalCoins' : bigint,
  'battleStats' : [] | [BattleStats],
  'bestScores' : BestScores,
}
export type StructureType = { 'house' : null } |
  { 'park' : null } |
  { 'shop' : null };
export type Time = bigint;
export interface _SERVICE {
  'createOrUpdatePlayerData' : ActorMethod<[[] | [string]], undefined>,
  'endGame' : ActorMethod<[], GameRunState>,
  'getGlobalGameState' : ActorMethod<[], [] | [GameState]>,
  'getPlayerData' : ActorMethod<[Principal], PlayerProfile>,
  'startGame' : ActorMethod<[GameMode], GameRunState>,
  'updateGame' : ActorMethod<[bigint], GameRunState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];