/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameRunState = IDL.Variant({
  'start' : IDL.Null,
  'gameOver' : IDL.Null,
  'running' : IDL.Null,
});
export const StructureType = IDL.Variant({
  'house' : IDL.Null,
  'park' : IDL.Null,
  'shop' : IDL.Null,
});
export const Time = IDL.Int;
export const MinigameScores = IDL.Record({
  'puzzleGame' : IDL.Nat,
  'reactionGame' : IDL.Nat,
});
export const CropType = IDL.Variant({
  'tomato' : IDL.Null,
  'carrot' : IDL.Null,
  'wheat' : IDL.Null,
});
export const BattleStats = IDL.Record({
  'winsCount' : IDL.Nat,
  'bestStreak' : IDL.Nat,
});
export const BestScores = IDL.Record({
  'car' : IDL.Nat,
  'farming' : IDL.Nat,
  'endlessRun' : IDL.Nat,
  'battle' : IDL.Nat,
  'cityBuilder' : IDL.Nat,
  'indoor' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'cityLayout' : IDL.Opt(IDL.Vec(IDL.Vec(StructureType))),
  'lastPlayed' : Time,
  'minigameScores' : IDL.Opt(MinigameScores),
  'farmPlots' : IDL.Opt(IDL.Vec(IDL.Vec(IDL.Opt(CropType)))),
  'displayName' : IDL.Opt(IDL.Text),
  'bestTime' : IDL.Opt(IDL.Nat),
  'totalCoins' : IDL.Nat,
  'battleStats' : IDL.Opt(BattleStats),
  'bestScores' : BestScores,
});
export const GameMode = IDL.Variant({
  'car' : IDL.Null,
  'farming' : IDL.Null,
  'endlessRun' : IDL.Null,
  'battle' : IDL.Null,
  'cityBuilder' : IDL.Null,
  'indoor' : IDL.Null,
});
export const GameState = IDL.Record({
  'mode' : GameMode,
  'score' : IDL.Nat,
  'state' : GameRunState,
  'coinsEarned' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdatePlayerData' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'endGame' : IDL.Func([], [GameRunState], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalGameState' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
  'getPlayerData' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startGame' : IDL.Func([GameMode], [GameRunState], []),
  'updateGame' : IDL.Func([IDL.Nat], [GameRunState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameRunState = IDL.Variant({
    'start' : IDL.Null,
    'gameOver' : IDL.Null,
    'running' : IDL.Null,
  });
  const StructureType = IDL.Variant({
    'house' : IDL.Null,
    'park' : IDL.Null,
    'shop' : IDL.Null,
  });
  const Time = IDL.Int;
  const MinigameScores = IDL.Record({
    'puzzleGame' : IDL.Nat,
    'reactionGame' : IDL.Nat,
  });
  const CropType = IDL.Variant({
    'tomato' : IDL.Null,
    'carrot' : IDL.Null,
    'wheat' : IDL.Null,
  });
  const BattleStats = IDL.Record({
    'winsCount' : IDL.Nat,
    'bestStreak' : IDL.Nat,
  });
  const BestScores = IDL.Record({
    'car' : IDL.Nat,
    'farming' : IDL.Nat,
    'endlessRun' : IDL.Nat,
    'battle' : IDL.Nat,
    'cityBuilder' : IDL.Nat,
    'indoor' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'cityLayout' : IDL.Opt(IDL.Vec(IDL.Vec(StructureType))),
    'lastPlayed' : Time,
    'minigameScores' : IDL.Opt(MinigameScores),
    'farmPlots' : IDL.Opt(IDL.Vec(IDL.Vec(IDL.Opt(CropType)))),
    'displayName' : IDL.Opt(IDL.Text),
    'bestTime' : IDL.Opt(IDL.Nat),
    'totalCoins' : IDL.Nat,
    'battleStats' : IDL.Opt(BattleStats),
    'bestScores' : BestScores,
  });
  const GameMode = IDL.Variant({
    'car' : IDL.Null,
    'farming' : IDL.Null,
    'endlessRun' : IDL.Null,
    'battle' : IDL.Null,
    'cityBuilder' : IDL.Null,
    'indoor' : IDL.Null,
  });
  const GameState = IDL.Record({
    'mode' : GameMode,
    'score' : IDL.Nat,
    'state' : GameRunState,
    'coinsEarned' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdatePlayerData' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'endGame' : IDL.Func([], [GameRunState], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalGameState' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
    'getPlayerData' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startGame' : IDL.Func([GameMode], [GameRunState], []),
    'updateGame' : IDL.Func([IDL.Nat], [GameRunState], []),
  });
};

export const init = ({ IDL }) => { return []; };